### ISSUE TITLE
缺少一个数据库配置文件

### ISSUE THREAD

**Issue by zhangdafu6688** [zhangdafu123/shop#1]
应该在上传一个db.properties文件，文件内容为
jdbc.driver=com.mysql.jdbc.Driver
jdbc.url=jdbc:mysql://localhost:3306/fsrm?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
jdbc.username=root
jdbc.password=123321

**Comment by zhangdafu123** [comment]
已经上传，谢谢建议

**Comment by zhangdafu6688** [comment]
应该在提交一个log4j.properties配置文件
